# id: 1
server:
    address: "server:12345"
loop:
    amount: 5
    period: "5s"
log:
    level: "INFO"
batch:
    maxAmount: 54
# bytes p/bet:
# 1 agency
# 60 firstname
# 60 lastname
# 8 document
# 10 birthdate
# 4 number
# 5 padding
# total: 148 bytes

# 8 kilobytes / 148 bytes = 55.35
# maxAmount: 54
# round to 54 including header (4 bytes) and & between bets (1 byte)
